name: Build & Release

on:
  push:
    branches:
      - main
#    paths:
#      - 'app/**'


jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: "app/"
          github_token: ${{ secrets.github_token }}
